### ISSUE TITLE
KDE's fork of Qt5

### ISSUE THREAD

**Issue by ghost** [crystalidea/qt-build-tools#3]
Maintained by KDE. Even if you don't own a commercial license of Qt, you still can use the latest bits of Qt5.

**Comment by kleuter** [comment]
Not sure you what you mean here

**Comment by ghost** [comment]
https://community.kde.org/Qt5PatchCollection

**Comment by ghost** [comment]
MSYS2 project also builds their Qt5 using this KDE's fork:

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-qt5-base/PKGBUILD
